name: kelas_flutter
description: Project belajar flutter di webmedia
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  cupertino_icons: ^1.0.2
  adaptive_components: ^0.0.9
  google_fonts: ^6.1.0
  firebase_core: ^2.16.0
  firebase_database: ^10.2.6
  cloud_firestore: ^4.9.3
  firebase_auth: ^4.10.0
  dio: ^5.3.3
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
